import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";   // ← IMPORTANTE
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 👉 Agregamos tu fuente Mondapick
const mondapick = localFont({
  src: "../../public/fonts/Mondapick.ttf", // asegúrate que exista esta ruta
  weight: "400",
  variable: "--font-mondapick",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mondapick.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
